// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1746061719);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1746061742);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1746061959);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1746061839);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1746061749);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1746061688);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0885ca2b-f482-402d-8104-88586caa2ae9}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1746061695");
user_pref("browser.startup.homepage_override.buildID", "20210415204500");
user_pref("browser.startup.homepage_override.mstone", "88.0");
user_pref("browser.startup.lastColdStartupCheck", 1746061692);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1746061741158");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "88.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "c1dd250fdd0148b599bcdd72ea430fd7");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210415204500");
user_pref("extensions.lastAppVersion", "88.0");
user_pref("extensions.lastPlatformVersion", "88.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"229419d2-88dc-4a63-acef-998da69fef3d\",\"formautofill@mozilla.org\":\"4edb8cbf-d726-4aeb-8cdc-3967050ee2ff\",\"pictureinpicture@mozilla.org\":\"4dd862bd-8016-4e97-8223-368f5047e4e8\",\"screenshots@mozilla.org\":\"583b484d-0d9b-4668-a22f-061e2fae5b87\",\"webcompat-reporter@mozilla.org\":\"01e2d6a1-efc8-4da9-a405-51cff0617d50\",\"webcompat@mozilla.org\":\"e354d54a-f585-4173-a735-2021bfbf5c78\",\"default-theme@mozilla.org\":\"e09864b4-c04a-441c-b839-41fe3cd088be\",\"google@search.mozilla.org\":\"1f02ca98-3d93-4c55-8e8f-6924c4edf28c\",\"drae@search.mozilla.org\":\"32c091af-6166-4b87-b4f1-42a3bc16f9e6\",\"wikipedia@search.mozilla.org\":\"588f1dc5-9b98-41f8-b67b-ff419e595bb9\",\"bing@search.mozilla.org\":\"f0f00d43-6107-4d48-8c0e-52456cef61cc\",\"ddg@search.mozilla.org\":\"51512e09-c747-4749-899b-ac93fd1c214c\",\"mercadolibre@search.mozilla.org\":\"9f2e44bd-12a1-4179-ad95-c81f5685013e\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1746061741);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1746061822);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-manager.buildID", "20210415204500");
user_pref("media.gmp-manager.lastCheck", 1746061821);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "38c0b9af-1331-41fe-b1ec-23c9ca5a631e");
user_pref("security.sandbox.plugin.tempDirSuffix", "ca8471d1-a3e6-4bc8-b2bf-49c70e820207");
user_pref("services.blocklist.plugins.checked", 1746061821);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_update_seconds", 1746061821);
user_pref("services.settings.main.sites-classification.last_check", 1746061821);
user_pref("toolkit.startup.last_success", 1746061687);
user_pref("toolkit.telemetry.cachedClientID", "6e80045e-f014-4ef7-a1a5-5ab536ad329c");
user_pref("toolkit.telemetry.previousBuildID", "20210415204500");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
